#ifndef _CONSTANTS_H__
#define _CONSTANTS_H__

#include <ArduinoJson.h>

#define DATE_TIME_ISO_LEN 26

#define CAPACITY_HTTP_ERROR (JSON_OBJECT_SIZE(2) + JSON_STRING_SIZE(32))
#define CAPACITY_INTERNAL_STATE (JSON_OBJECT_SIZE(4) + JSON_STRING_SIZE(DATE_TIME_ISO_LEN))
#define CAPACITY_SET_POINT (JSON_OBJECT_SIZE(2) + JSON_STRING_SIZE(16))
#define CAPACITY_DAILY_SCHEDULE (JSON_OBJECT_SIZE(2) + JSON_ARRAY_SIZE(12) + JSON_STRING_SIZE(16))
#define CAPACITY_USER_SETTINGS_MANAGER (JSON_OBJECT_SIZE(6) + CAPACITY_SET_POINT * 4 + CAPACITY_DAILY_SCHEDULE * 4)

#endif